"""app_versions jadvali (majburiy yangilanish)

Revision ID: 4c9e1e3f9f5c
Revises: 3a7f68c8181a
Create Date: 2026-09-18 23:52:13.411581
"""
from alembic import op
import sqlalchemy as sa


revision = '4c9e1e3f9f5c'
down_revision = '3a7f68c8181a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app', sa.String(length=32), nullable=False),
    sa.Column('min_version_code', sa.Integer(), nullable=False),
    sa.Column('store_url', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_versions_app'), 'app_versions', ['app'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_versions_app'), table_name='app_versions')
    op.drop_table('app_versions')
    # ### end Alembic commands ###
