/** Kategoriya kartochkalari uchun yumshoq pastel ranglar (30 ta). */
export const SOFT_CATEGORY_COLORS: string[] = [
  "#E1F3D8",
  "#DCFCE7",
  "#E8F5E9",
  "#F0FDF4",
  "#D1FAE5",
  "#CCFBF1",
  "#CDE3FC",
  "#DBEAFE",
  "#E0F2FE",
  "#ECFEFF",
  "#E0E7FF",
  "#EEF2FF",
  "#FEF9C3",
  "#FEF3C7",
  "#FFF7ED",
  "#FFEDD5",
  "#FDF6E3",
  "#F5F0E6",
  "#FCE7F3",
  "#FDF2F8",
  "#F3E8FF",
  "#EDE9FE",
  "#F5E6F0",
  "#FAE8FF",
  "#F1F5F9",
  "#F8FAFC",
  "#ECFDF5",
  "#FEF2F2",
  "#FFF1F2",
  "#F0FDFA",
];

export const DEFAULT_CATEGORY_COLOR = SOFT_CATEGORY_COLORS[0];
